FROM node:16

WORKDIR /home/node

RUN mkdir frontend backend

COPY ./package*.json ./backend
# RUN cd ./backend && npm install

# COPY ../frontend/package*.json ./frontend
# RUN cd ./frontend && npm install
# 
# COPY . ./backend
# COPY ../frontend/* ./frontend
# 
# RUN cd ./backend && npm run build

CMD ["sleep", "infinity"]
